name: ss-gas

services:
  postgres:
    image: postgres
    container_name: ss-gas-postgres
    environment:
      POSTGRES_DB: ss-gas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ss-gas_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  ss-gas_postgres_data:
